# Generated by Django 4.2.7 on 2023-11-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor_number', models.PositiveIntegerField()),
                ('apartment_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
