# Generated by Django 4.2.7 on 2023-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('karfarma', 'Karfarma'), ('engineer', 'Engineer'), ('employee', 'Employee')], max_length=100),
        ),
    ]
