# Generated by Django 4.2.7 on 2023-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('karfarma', 'کارفرما'), ('engineer', 'مهندس'), ('employee', 'پیمانکار')], max_length=100),
        ),
    ]
