# Generated by Django 4.2.7 on 2023-11-19 09:55

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at_alter_task_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_added',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
