# Generated by Django 4.2.7 on 2023-11-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_followup_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
