# Generated by Django 4.2.7 on 2023-11-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_followup_date_added_alter_task_completed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_date',
        ),
        migrations.AlterField(
            model_name='followup',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
