# Generated by Django 4.2.7 on 2023-11-21 09:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_completed_date_alter_followup_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
